name: eco_wake_sleep_sub
version: 'v1.0.0'
main: io.github.ant_cave.eco_wake_sleep_sub.Eco_wake_sleep_sub
api-version: '1.21'
authors: [ ANTmmmmm ]
website: ant-cave.github.io

commands:
  status:
    description: Check the current plugin status
    usage: /status
    permission: eco_wake_sleep_sub.status
  wake:
    description: Check the current plugin status
    usage: /wake <server_mac>
    permission: eco_wake_sleep_sub.wake
  ping:
    description: Check the current plugin status
    usage: /ping <server_ip>
    permission: eco_wake_sleep_sub.ping
  connect:
    description: Connect a player to another server
    usage: /connect <playername> <servername>
    permission: eco_wake_sleep_sub.connect
  tcping:
    description: Check TCP port connectivity
    usage: /tcping <host> <port>
    permission: eco_wake_sleep_sub.tcping
  mcping:
    description: Check Minecraft server connectivity
    usage: /mcping [host] [port]
    permission: eco_wake_sleep_sub.mcping
  reload:
    description: Reload plugin configuration
    usage: /reload
    permission: eco_wake_sleep_sub.reload
  runningstatus:
    description: Check remote server running status
    usage: /runningstatus
    permission: eco_wake_sleep_sub.runningstatus

permissions:
  eco_wake_sleep_sub.status:
    description: Allows the user to check plugin status
    default: op
  eco_wake_sleep_sub.wake:
    description: Allows the user to wake the server
    default: op
  eco_wake_sleep_sub.ping:
    description: Allows the user to ping server IP
    default: op
  eco_wake_sleep_sub.connect:
    description: Allows the user to connect players to other servers
    default: op
  eco_wake_sleep_sub.tcping:
    description: Allows the user to check TCP port connectivity
    default: op
  eco_wake_sleep_sub.mcping:
    description: Allows the user to check Minecraft server connectivity
    default: op
  eco_wake_sleep_sub.reload:
    description: Allows the user to reload plugin configuration
    default: op
  eco_wake_sleep_sub.runningstatus:
    description: Allows the user to check remote server running status
    default: op
